# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: samsa/api/health_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import samsa.api.health_service_pb2 as samsa_dot_api_dot_health__service__pb2


class HealthService(Protocol):
    async def check(self, request: samsa_dot_api_dot_health__service__pb2.HealthCheckRequest, ctx: RequestContext) -> samsa_dot_api_dot_health__service__pb2.HealthCheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HealthServiceASGIApplication(ConnectASGIApplication[HealthService]):
    def __init__(self, service: HealthService | AsyncGenerator[HealthService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/samsa.api.v2.HealthService/Check": Endpoint.unary(
                    method=MethodInfo(
                        name="Check",
                        service_name="samsa.api.v2.HealthService",
                        input=samsa_dot_api_dot_health__service__pb2.HealthCheckRequest,
                        output=samsa_dot_api_dot_health__service__pb2.HealthCheckResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/samsa.api.v2.HealthService"


class HealthServiceClient(ConnectClient):
    async def check(
        self,
        request: samsa_dot_api_dot_health__service__pb2.HealthCheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> samsa_dot_api_dot_health__service__pb2.HealthCheckResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Check",
                service_name="samsa.api.v2.HealthService",
                input=samsa_dot_api_dot_health__service__pb2.HealthCheckRequest,
                output=samsa_dot_api_dot_health__service__pb2.HealthCheckResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class HealthServiceSync(Protocol):
    def check(self, request: samsa_dot_api_dot_health__service__pb2.HealthCheckRequest, ctx: RequestContext) -> samsa_dot_api_dot_health__service__pb2.HealthCheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HealthServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: HealthServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/samsa.api.v2.HealthService/Check": EndpointSync.unary(
                    method=MethodInfo(
                        name="Check",
                        service_name="samsa.api.v2.HealthService",
                        input=samsa_dot_api_dot_health__service__pb2.HealthCheckRequest,
                        output=samsa_dot_api_dot_health__service__pb2.HealthCheckResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/samsa.api.v2.HealthService"


class HealthServiceClientSync(ConnectClientSync):
    def check(
        self,
        request: samsa_dot_api_dot_health__service__pb2.HealthCheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> samsa_dot_api_dot_health__service__pb2.HealthCheckResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Check",
                service_name="samsa.api.v2.HealthService",
                input=samsa_dot_api_dot_health__service__pb2.HealthCheckRequest,
                output=samsa_dot_api_dot_health__service__pb2.HealthCheckResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
