# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: samsa/api/health_service.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'samsa/api/health_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esamsa/api/health_service.proto\x12\x0csamsa.api.v2\".\n\x12HealthCheckRequest\x12\x18\n\x07service\x18\x01 \x01(\tR\x07service\"-\n\x13HealthCheckResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status2]\n\rHealthService\x12L\n\x05\x43heck\x12 .samsa.api.v2.HealthCheckRequest\x1a!.samsa.api.v2.HealthCheckResponseB\xb0\x01\n\x10\x63om.samsa.api.v2B\x12HealthServiceProtoP\x01Z6github.com/justblue/samsa/internal/gen/samsa/api;apiv2\xa2\x02\x03SAX\xaa\x02\x0cSamsa.Api.V2\xca\x02\x0cSamsa\\Api\\V2\xe2\x02\x18Samsa\\Api\\V2\\GPBMetadata\xea\x02\x0eSamsa::Api::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'samsa.api.health_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.samsa.api.v2B\022HealthServiceProtoP\001Z6github.com/justblue/samsa/internal/gen/samsa/api;apiv2\242\002\003SAX\252\002\014Samsa.Api.V2\312\002\014Samsa\\Api\\V2\342\002\030Samsa\\Api\\V2\\GPBMetadata\352\002\016Samsa::Api::V2'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=48
  _globals['_HEALTHCHECKREQUEST']._serialized_end=94
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=96
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=141
  _globals['_HEALTHSERVICE']._serialized_start=143
  _globals['_HEALTHSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
