version: "2"
run:
    deadline: 10m

linters:
    enable:
        - copyloopvar
        - errcheck
        - gocritic
        - gosec
        - govet
        - ineffassign
        - lll
        - misspell
        - revive
        - staticcheck
        - unconvert
        - unparam
        - unused

linters-settings:
    gci:
        sections:
            - standard # Captures all standard packages if they do not match another section.
            - default # Contains all imports that could not be matched to another section type.
            - prefix(github.com/justblue/samsa) # Groups all imports with the specified Prefix.
    goimports:
        # put imports beginning with prefix after 3rd-party packages;
        # it's a comma-separated list of prefixes
        local-prefixes: github.com/justblue/samsa
    gofmt:
        simplify: true
    unparam:
        check-exported: false

issues:
    exclude-rules:
        - path: zz_generated
          linters:
              - goimports
        - linters:
              - staticcheck
          text: "SA1019:"
        - path: test/e2e
          linters:
              - bodyclose
    # Show the complete output
    max-issues-per-linter: 0
    max-same-issues: 0
