# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: samsa/api/recommendation/recommendation_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import samsa.api.recommendation.recommendation_service_pb2 as samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2


class RecommendationService(Protocol):
    def get_recommendations(self, request: samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationRequest, ctx: RequestContext) -> AsyncIterator[samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def health(self, request: samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckRequest, ctx: RequestContext) -> samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class RecommendationServiceASGIApplication(ConnectASGIApplication[RecommendationService]):
    def __init__(self, service: RecommendationService | AsyncGenerator[RecommendationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/samsa.api.recommendation.v1.RecommendationService/GetRecommendations": Endpoint.server_stream(
                    method=MethodInfo(
                        name="GetRecommendations",
                        service_name="samsa.api.recommendation.v1.RecommendationService",
                        input=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationRequest,
                        output=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_recommendations,
                ),
                "/samsa.api.recommendation.v1.RecommendationService/Health": Endpoint.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="samsa.api.recommendation.v1.RecommendationService",
                        input=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckRequest,
                        output=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.health,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/samsa.api.recommendation.v1.RecommendationService"


class RecommendationServiceClient(ConnectClient):
    def get_recommendations(
        self,
        request: samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GetRecommendations",
                service_name="samsa.api.recommendation.v1.RecommendationService",
                input=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationRequest,
                output=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def health(
        self,
        request: samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="samsa.api.recommendation.v1.RecommendationService",
                input=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckRequest,
                output=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class RecommendationServiceSync(Protocol):
    def get_recommendations(self, request: samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationRequest, ctx: RequestContext) -> Iterator[samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def health(self, request: samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckRequest, ctx: RequestContext) -> samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class RecommendationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: RecommendationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/samsa.api.recommendation.v1.RecommendationService/GetRecommendations": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="GetRecommendations",
                        service_name="samsa.api.recommendation.v1.RecommendationService",
                        input=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationRequest,
                        output=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_recommendations,
                ),
                "/samsa.api.recommendation.v1.RecommendationService/Health": EndpointSync.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="samsa.api.recommendation.v1.RecommendationService",
                        input=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckRequest,
                        output=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.health,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/samsa.api.recommendation.v1.RecommendationService"


class RecommendationServiceClientSync(ConnectClientSync):
    def get_recommendations(
        self,
        request: samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GetRecommendations",
                service_name="samsa.api.recommendation.v1.RecommendationService",
                input=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationRequest,
                output=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.RecommendationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def health(
        self,
        request: samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="samsa.api.recommendation.v1.RecommendationService",
                input=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckRequest,
                output=samsa_dot_api_dot_recommendation_dot_recommendation__service__pb2.HealthCheckResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
